package GeoPharmacie;


import java.util.Date;


//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Commande.java
//  @ Date : 10/27/2018
//  @ Author : 
//
//




public class Commande {
     private int NumCommande;
     private Date DateCommande;
     private String EtatCommande;

    public Commande(int NumCommande, Date DateCommande, String EtatCommande) {
        this.NumCommande = NumCommande;
        this.DateCommande = DateCommande;
        this.EtatCommande = EtatCommande;
    }

    Commande(int numeroCommande, String dateCommande, String EtatCommade) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void setNumCommande(int NumCommande) {
        this.NumCommande = NumCommande;
    }

    public void setDateCommande(Date DateCommande) {
        this.DateCommande = DateCommande;
    }

    public void setEtatCommande(String EtatCommande) {
        this.EtatCommande = EtatCommande;
    }

    public int getNumCommande() {
        return NumCommande;
    }

    public Date getDateCommande() {
        return DateCommande;
    }

    public String getEtatCommande() {
        return EtatCommande;
    }
     
}
