package GeoPharmacie;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ligne de commande.java
//  @ Date : 10/27/2018
//  @ Author : 
//
//




public class LigneDeCommande {
     private float Quantite;

    public float getQuantite() {
        return Quantite;
    }

    public void setQuantite(float Quantite) {
        this.Quantite = Quantite;
    }

    public LigneDeCommande(float Quantite) {
        this.Quantite = Quantite;
    }
     
}
